
from gwBackend.scripts.First_Admin_User import create_admin_user_if_not_exists


def run_scripts(execute_create_admin_user_if_not_exists=False):
    create_admin_user_if_not_exists(execute_create_admin_user_if_not_exists)